/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peoplepage;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import peoplepage.PeoplePage;

/**
 *
 * @author Kirby
 */
public class AddEmp extends javax.swing.JFrame {
    /**
     * Creates new form AddEmp
     */
    AddEmpController aec = new AddEmpController();
    
    private String name;
    private AddEmp(){
        
    }
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    
    public AddEmp(String name) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        setName(name);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        background_addEmployee = new javax.swing.JLabel();
        AddEmpAdd = new javax.swing.JButton();
        AddEmpClear = new javax.swing.JButton();
        AddEmpCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New User");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        txtFirstName.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtFirstName);
        txtFirstName.setBounds(280, 160, 280, 40);

        txtLastName.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtLastName);
        txtLastName.setBounds(280, 210, 280, 40);

        txtUsername.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(279, 270, 280, 40);

        txtPassword.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword);
        txtPassword.setBounds(280, 330, 280, 40);

        txtConfirmPassword.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtConfirmPassword);
        txtConfirmPassword.setBounds(279, 380, 280, 40);

        txtEmail.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail);
        txtEmail.setBounds(279, 440, 280, 40);

        txtContactNumber.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtContactNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });
        jPanel2.add(txtContactNumber);
        txtContactNumber.setBounds(279, 490, 280, 40);

        txtAddress.setFont(new java.awt.Font("Montserrat Light", 1, 14)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 158, 9), 2));
        jPanel2.add(txtAddress);
        txtAddress.setBounds(279, 550, 280, 40);

        background_addEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FORMADJUSTED-02.png"))); // NOI18N
        jPanel2.add(background_addEmployee);
        background_addEmployee.setBounds(0, 0, 600, 700);

        AddEmpAdd.setText("ADD");
        AddEmpAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpAddActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpAdd);
        AddEmpAdd.setBounds(280, 620, 70, 40);

        AddEmpClear.setText("CLEAR");
        AddEmpClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpClearActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpClear);
        AddEmpClear.setBounds(360, 620, 90, 40);

        AddEmpCancel.setText("CANCEL");
        AddEmpCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpCancelActionPerformed(evt);
            }
        });
        jPanel2.add(AddEmpCancel);
        AddEmpCancel.setBounds(460, 623, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpClearActionPerformed
        aec.clear(this);
        txtConfirmPassword.setText("");
    }//GEN-LAST:event_AddEmpClearActionPerformed

    private void AddEmpAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpAddActionPerformed
        if(txtFirstName.getText().trim().equals("") || txtLastName.getText().trim().equals("") 
                || txtUsername.getText().trim().equals("") || txtPassword.getText().trim().equals("") 
                || txtConfirmPassword.getText().trim().equals("") || txtEmail.getText().trim().equals("")
                || txtContactNumber.getText().trim().equals("") || txtAddress.getText().trim().equals("")
                ) {
            JOptionPane.showMessageDialog(null, "Failed! Please fill up!");
        } 
        
        else if (!txtPassword.getText().equals(txtConfirmPassword.getText())) {
            JOptionPane.showMessageDialog(null, "Passwords don't match!");
        }
        
        
        else {
            String firstName = txtFirstName.getText();
            String lastName = txtLastName.getText();
            String username = txtUsername.getText();
            String password = txtPassword.getText();
            String email = txtEmail.getText();
            String contactNumber = txtContactNumber.getText();
            String address = txtAddress.getText();
            
            if (JOptionPane.showConfirmDialog(null, "Are you sure you want to add this?", "Confirm Adding",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                
                try {
                    aec.add(firstName,lastName,username,password,email,contactNumber,address);
                    
                    this.dispose();
                    PeoplePage peop = new PeoplePage(this.getName());
                    peop.getLblUser().setText("Welcome, "+this.getName());
                    peop.setVisible(true);
                    peop.setExtendedState(JFrame.MAXIMIZED_BOTH);
                } catch (IOException ex) {
                    Logger.getLogger(AddEmp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_AddEmpAddActionPerformed

    private void AddEmpCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpCancelActionPerformed
        try {
            this.dispose();
            PeoplePage peop = new PeoplePage(this.getName());
            peop.getLblUser().setText("Welcome "+this.getName());
            peop.setVisible(true);
            peop.setExtendedState(JFrame.MAXIMIZED_BOTH);
        } catch (IOException ex) {
            Logger.getLogger(AddEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddEmpCancelActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmp().setVisible(true);
            }
        });
    }
    
     

    
    
    
    
    //Getters
    public JTextField getTxtFname() {
        return txtFirstName;
    }

    public JTextField getTxtLname() {
        return txtLastName;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }
    
    public JPasswordField getTxtConfirm() {
        return txtConfirmPassword;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }
    
    public JTextField getTxtEmail(){
        return txtEmail;
    }
    
    public JTextField getTxtContactNo(){
        return txtContactNumber;
    }
    
    public JTextField getTxtAddress(){
        return txtAddress;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmpAdd;
    private javax.swing.JButton AddEmpCancel;
    private javax.swing.JButton AddEmpClear;
    private javax.swing.JLabel background_addEmployee;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
}
