/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminpage;

import cashierpage.CashierPage;
import cashierpage.ChangeFund;
import delivery.DeliveryPage;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import login.Login;
import models.SalesModel;
import models.TransactionModel;
import peoplepage.PeoplePage;
import productpage.ProductPage;
import stockpage.StockPage;

/**
 *
 * @author Allysha
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    //AdminPageController apc = new AdminPageController(); //calls adminpage controller
    
    /*
    private String name;
    
    public String getName(){
        return name;
    }
    
    public void setName(String name){
        this.name = name;
    }
    */
    private int id;
    JFrame frame = new JFrame();
    
    public AdminPage() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
    }
    
    public AdminPage(String name,int id) {
        initComponents();
         
        this.setLocationRelativeTo(null);
        setName(name);
        setId(id);
    }
    
      public AdminPage(String name) {
        initComponents();
         
        this.setLocationRelativeTo(null);
        setName(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        company = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnCashier = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        btnPeople = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnDelivery = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDelivery1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        company.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        company.setText("Tanciong's General Merchandise");

        lblUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUser.setText("jLabel1");

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnCashier.setBackground(new java.awt.Color(255, 255, 255));
        btnCashier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCashier.setText("CASHIER");
        btnCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierActionPerformed(evt);
            }
        });

        btnProducts.setBackground(new java.awt.Color(255, 255, 255));
        btnProducts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProducts.setText("PRODUCTS");
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });

        btnPeople.setBackground(new java.awt.Color(255, 255, 255));
        btnPeople.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPeople.setText("PEOPLE");
        btnPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(255, 255, 255));
        btnReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReports.setText("REPORTS");

        btnDelivery.setBackground(new java.awt.Color(255, 255, 255));
        btnDelivery.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelivery.setText("DELIVERY");
        btnDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 165, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btnDelivery1.setBackground(new java.awt.Color(255, 255, 255));
        btnDelivery1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelivery1.setText("STOCKS");
        btnDelivery1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelivery1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(company)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCashier)
                    .addComponent(btnDelivery1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeople)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelivery)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(company)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelivery1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        SalesModel sm = new SalesModel();
        TransactionModel tm = new TransactionModel();
        int res;
        float total;
        res =JOptionPane.showConfirmDialog(frame, "Are you sure do you want to log out?(Your Total Sales Will be Counted.)");
        if(res == JOptionPane.YES_OPTION){
            total = tm.computeTotalSales(getId());
            sm.addTotalSales(getId(), total);
            JOptionPane.showMessageDialog(frame,"You have Successfully logged out, your total sales is P"+total+"");
            Login l = new Login();
            l.setVisible(true);
             this.setVisible(false);
         
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    public void logout(){
        SalesModel sm = new SalesModel();
        TransactionModel tm = new TransactionModel();
        int res;
        float total;
        res =JOptionPane.showConfirmDialog(frame, "Are you sure do you want to log out?(Your Total Sales Will be Counted.)");
        if(res == JOptionPane.YES_OPTION){
            total = tm.computeTotalSales(getId());
            sm.addTotalSales(getId(), total);
            JOptionPane.showMessageDialog(frame,"You have Successfully logged out, your total sales is P"+total+"");
            Login l = new Login();
            l.setVisible(true);
             this.setVisible(false);
         
            this.dispose();
        }
    }
    private void btnCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierActionPerformed
        SalesModel sm = new SalesModel();
        if(sm.checkDate()>=1){
            CashierPage cp = new CashierPage(this.getName(),this.getId());
                        cp.getLblUser().setText("Welcome, "+this.getName());
                        cp.setVisible(true);
                        cp.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        this.dispose();
        }else{
        ChangeFund cf = new ChangeFund(this.getName(),this.getId()); //link the changefund and gets the name/username when logged in from the login
        cf.getLblUser().setText("Welcome, "+this.getName()); //displays the welcome message with the name/username

        cf.setVisible(true);
        this.dispose();
        
        //cf.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        }
    }//GEN-LAST:event_btnCashierActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        ProductPage prp = new ProductPage(this.getName());
        prp.getLblUser().setText("Welcome, "+this.getName());
        
        prp.setVisible(true);
        this.dispose();
        
        prp.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleActionPerformed
        PeoplePage peop = new PeoplePage(this.getName());
        peop.getLblUser().setText("Welcome, "+this.getName());
        
        peop.setVisible(true);
        this.dispose();
        
        peop.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnPeopleActionPerformed

    private void btnDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryActionPerformed
        DeliveryPage dp = new DeliveryPage(this.getName());
        dp.getLblUser().setText("Welcome, "+this.getName());
        
        dp.setVisible(true);
        this.dispose();
        
        dp.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnDeliveryActionPerformed

    private void btnDelivery1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelivery1ActionPerformed
       StockPage sp = new StockPage(this.getName());
       sp.getLblUser().setText("Welcome, "+this.getName());
       
       sp.setVisible(true);
       this.dispose();
       sp.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }//GEN-LAST:event_btnDelivery1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnDelivery;
    private javax.swing.JButton btnDelivery1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPeople;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel company;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

  public void setId(int id){
      this.id = id;
  }
  
  public int getId(){
      return id;
  }
}
